/* eslint-disable indent */
/* eslint-disable quote-props */
/* eslint-disable quotes */
/* eslint-disable react/jsx-filename-extension */
import React from 'react';
import ReactDOM from 'react-dom';
import { Provider } from 'react-redux';
import { createStore, compose } from 'redux';
import reducer from './reducers';
import App from './routes/App';

const initialState = {
  "user": {},
  "playing": {},
  "MySites": [],
  "food": [
      {
        "id": 2,
        "nameSite": "Catedral-Zipaquira",
        "description": "bla bla bla bla",
        "rating": 10,
        "type": "food",
        "ccomments": "16+",
        "address": "Calle 100# 13-21",
        "city": "Bogota",
        "country": "Colombia",
        "socialMedia": [{ "gmail": "sitio@gmail.com", "facebook": "sitio@gmail.com" }],
        "images": "https://www.ecestaticos.com/imagestatic/clipping/1ed/a44/1eda44daf5f75ca868b7eb9bf93396e4/por-que-el-desayuno-es-la-comida-mas-importante-si-quieres-estar-delgado.jpg?mtime=1500455115",
        "source": "https://www.kienyke.com/wp-content/uploads/2018/05/avistamientos.jpeg",
        "coordinates": [{ "lat": 4.6560716, "lng": -74.0595918 }],
      },
      {
        "id": 3,
        "nameSite": "Catedral-Zipaquira",
        "description": "bla bla bla bla",
        "rating": 10,
        "type": "food",
        "ccomments": "16+",
        "address": "Calle 100# 13-21",
        "city": "Bogota",
        "country": "Colombia",
        "socialMedia": [{ "gmail": "sitio@gmail.com", "facebook": "sitio@gmail.com" }],
        "images": "https://blog.seccionamarilla.com.mx/wp-content/uploads/2017/11/comida_naviden%CC%83a-770x578.jpg",
        "source": "https://www.kienyke.com/wp-content/uploads/2018/05/avistamientos.jpeg",
        "coordinates": [{ "lat": 4.6560716, "lng": -74.0595918 }],
      },
      {
        "id": 4,
        "nameSite": "Catedral-Zipaquira",
        "description": "bla bla bla bla",
        "rating": 10,
        "type": "food",
        "ccomments": "16+",
        "address": "Calle 100# 13-21",
        "city": "Bogota",
        "country": "Colombia",
        "socialMedia": [{ "gmail": "sitio@gmail.com", "facebook": "sitio@gmail.com" }],
        "images": "https://i1.wp.com/thehappening.com/wp-content/uploads/2017/01/comida-healthy.jpg?fit=1024%2C694&ssl=1",
        "source": "https://www.kienyke.com/wp-content/uploads/2018/05/avistamientos.jpeg",
        "coordinates": [{ "lat": 4.6560716, "lng": -74.0595918 }],
      },
      {
        "id": 5,
        "nameSite": "Catedral-Zipaquira",
        "description": "bla bla bla bla",
        "rating": 10,
        "type": "food",
        "ccomments": "16+",
        "address": "Calle 100# 13-21",
        "city": "Bogota",
        "country": "Colombia",
        "socialMedia": [{ "gmail": "sitio@gmail.com", "facebook": "sitio@gmail.com" }],
        "images": "https://t2.rg.ltmcdn.com/es/images/4/2/6/los_15_platos_mas_tipicos_de_mexico_71624_600.jpg",
        "source": "https://www.kienyke.com/wp-content/uploads/2018/05/avistamientos.jpeg",
        "coordinates": [{ "lat": 4.6560716, "lng": -74.0595918 }],
      },
      {
        "id": 6,
        "nameSite": "Catedral-Zipaquira",
        "description": "bla bla bla bla",
        "rating": 10,
        "type": "food",
        "ccomments": "16+",
        "address": "Calle 100# 13-21",
        "city": "Bogota",
        "country": "Colombia",
        "socialMedia": [{ "gmail": "sitio@gmail.com", "facebook": "sitio@gmail.com" }],
        "images": "https://www.tootay.com/wp-content/uploads/2017/07/600-13093.jpeg",
        "source": "https://www.kienyke.com/wp-content/uploads/2018/05/avistamientos.jpeg",
        "coordinates": [{ "lat": 4.6560716, "lng": -74.0595918 }],
      },
      {
        "id": 7,
        "nameSite": "Catedral-Zipaquira",
        "description": "bla bla bla bla",
        "rating": 10,
        "type": "food",
        "ccomments": "16+",
        "address": "Calle 100# 13-21",
        "city": "Bogota",
        "country": "Colombia",
        "socialMedia": [{ "gmail": "sitio@gmail.com", "facebook": "sitio@gmail.com" }],
        "images": "https://hablemosdeculturas.com/wp-content/uploads/2017/12/Comida-Francesa-08.jpg",
        "source": "https://www.kienyke.com/wp-content/uploads/2018/05/avistamientos.jpeg",
        "coordinates": [{ "lat": 4.6560716, "lng": -74.0595918 }],
      },
    ],
    "coffee": [
      {
        "id": 8,
        "nameSite": "Catedral-Zipaquira",
        "description": "bla bla bla bla",
        "rating": 10,
        "type": "food",
        "ccomments": "16+",
        "address": "Calle 100# 13-21",
        "city": "Bogota",
        "country": "Colombia",
        "socialMedia": [{ "gmail": "sitio@gmail.com", "facebook": "sitio@gmail.com" }],
        "images": "https://visit.gent.be/sites/default/files/styles/header_mobile/public/img/poi/hero/PuurGent-DT007776.JPG?itok=HdM0jHs9",
        "source": "https://www.kienyke.com/wp-content/uploads/2018/05/avistamientos.jpeg",
        "coordinates": [{ "lat": 4.6560716, "lng": -74.0595918 }],
      },
      {
        "id": 9,
        "nameSite": "Catedral-Zipaquira",
        "description": "bla bla bla bla",
        "rating": 10,
        "type": "food",
        "ccomments": "16+",
        "address": "Calle 100# 13-21",
        "city": "Bogota",
        "country": "Colombia",
        "socialMedia": [{ "gmail": "sitio@gmail.com", "facebook": "sitio@gmail.com" }],
        "images": "https://media-cdn.tripadvisor.com/media/photo-s/13/7f/54/8e/photo3jpg.jpg",
        "source": "https://www.kienyke.com/wp-content/uploads/2018/05/avistamientos.jpeg",
        "coordinates": [{ "lat": 4.6560716, "lng": -74.0595918 }],
      },
      {
        "id": 10,
        "nameSite": "Catedral-Zipaquira",
        "description": "bla bla bla bla",
        "rating": 10,
        "type": "food",
        "ccomments": "16+",
        "address": "Calle 100# 13-21",
        "city": "Bogota",
        "country": "Colombia",
        "socialMedia": [{ "gmail": "sitio@gmail.com", "facebook": "sitio@gmail.com" }],
        "images": "https://www.apasionadosporelcafe.com/wp-content/uploads/2018/02/2018-02-01-4.png",
        "source": "https://www.kienyke.com/wp-content/uploads/2018/05/avistamientos.jpeg",
        "coordinates": [{ "lat": 4.6560716, "lng": -74.0595918 }],
      },
      {
        "id": 11,
        "nameSite": "Catedral-Zipaquira",
        "description": "bla bla bla bla",
        "rating": 10,
        "type": "food",
        "ccomments": "16+",
        "address": "Calle 100# 13-21",
        "city": "Bogota",
        "country": "Colombia",
        "socialMedia": [{ "gmail": "sitio@gmail.com", "facebook": "sitio@gmail.com" }],
        "images": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTfZNGZsPrc9vOUBbbTE2ec5jGYPd09ZiH_WIqW_H0ddTzZkh6n8g&s",
        "source": "https://www.kienyke.com/wp-content/uploads/2018/05/avistamientos.jpeg",
        "coordinates": [{ "lat": 4.6560716, "lng": -74.0595918 }],
      },
      {
        "id": 12,
        "nameSite": "Catedral-Zipaquira",
        "description": "bla bla bla bla",
        "rating": 10,
        "type": "Diversión",
        "ccomments": "16+",
        "address": "Calle 100# 13-21",
        "city": "Bogota",
        "country": "Colombia",
        "socialMedia": [{ "gmail": "sitio@gmail.com", "facebook": "sitio@gmail.com" }],
        "images": "https://media-cdn.tripadvisor.com/media/photo-s/0c/0e/61/91/cafe-amore.jpg",
        "source": "https://www.kienyke.com/wp-content/uploads/2018/05/avistamientos.jpeg",
        "coordinates": [{ "lat": 4.6560716, "lng": -74.0595918 }],
      },
      {
        "id": 13,
        "nameSite": "Catedral-Zipaquira",
        "description": "bla bla bla bla",
        "rating": 10,
        "type": "Diversión",
        "ccomments": "16+",
        "address": "Calle 100# 13-21",
        "city": "Bogota",
        "country": "Colombia",
        "socialMedia": [{ "gmail": "sitio@gmail.com", "facebook": "sitio@gmail.com" }],
        "images": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRxbTXZjTt6_Xne2-KiwW8IJzh1nsrVOWPOKd4MpMtGorAtr97G&s",
        "source": "https://www.kienyke.com/wp-content/uploads/2018/05/avistamientos.jpeg",
        "coordinates": [{ "lat": 4.6560716, "lng": -74.0595918 }],
      },
    ],
    "night": [
      {
        "id": 14,
        "nameSite": "Catedral-Zipaquira",
        "description": "bla bla bla bla",
        "rating": 15,
        "type": "Diversión",
        "ccomments": "16+",
        "address": "Calle 100# 13-21",
        "city": "Bogota",
        "country": "Colombia",
        "socialMedia": [{ "gmail": "sitio@gmail.com", "facebook": "sitio@gmail.com" }],
        "images": "https://www.ecestaticos.com/imagestatic/clipping/1ed/a44/1eda44daf5f75ca868b7eb9bf93396e4/por-que-el-desayuno-es-la-comida-mas-importante-si-quieres-estar-delgado.jpg?mtime=1500455115",
        "source": "https://www.kienyke.com/wp-content/uploads/2018/05/avistamientos.jpeg",
        "coordinates": [{ "lat": 4.6560716, "lng": -74.0595918 }],
      },
      {
        "id": 16,
        "nameSite": "Catedral-Zipaquira",
        "description": "bla bla bla bla",
        "rating": 10,
        "type": "Diversión",
        "ccomments": "16+",
        "address": "Calle 100# 13-21",
        "city": "Bogota",
        "country": "Colombia",
        "socialMedia": [{ "gmail": "sitio@gmail.com", "facebook": "sitio@gmail.com" }],
        "images": "https://blog.seccionamarilla.com.mx/wp-content/uploads/2017/11/comida_naviden%CC%83a-770x578.jpg",
        "source": "https://www.kienyke.com/wp-content/uploads/2018/05/avistamientos.jpeg",
        "coordinates": [{ "lat": 4.6560716, "lng": -74.0595918 }],
      },
      {
        "id": 17,
        "nameSite": "Catedral-Zipaquira",
        "description": "bla bla bla bla",
        "rating": 10,
        "type": "Diversión",
        "ccomments": "16+",
        "address": "Calle 100# 13-21",
        "city": "Bogota",
        "country": "Colombia",
        "socialMedia": [{ "gmail": "sitio@gmail.com", "facebook": "sitio@gmail.com" }],
        "images": "https://i1.wp.com/thehappening.com/wp-content/uploads/2017/01/comida-healthy.jpg?fit=1024%2C694&ssl=1",
        "source": "https://www.kienyke.com/wp-content/uploads/2018/05/avistamientos.jpeg",
        "coordinates": [{ "lat": 4.6560716, "lng": -74.0595918 }],
      },
      {
        "id": 18,
        "nameSite": "Catedral-Zipaquira",
        "description": "bla bla bla bla",
        "rating": 10,
        "type": "Diversión",
        "ccomments": "16+",
        "address": "Calle 100# 13-21",
        "city": "Bogota",
        "country": "Colombia",
        "socialMedia": [{ "gmail": "sitio@gmail.com", "facebook": "sitio@gmail.com" }],
        "images": "https://t2.rg.ltmcdn.com/es/images/4/2/6/los_15_platos_mas_tipicos_de_mexico_71624_600.jpg",
        "source": "https://www.kienyke.com/wp-content/uploads/2018/05/avistamientos.jpeg",
        "coordinates": [{ "lat": 4.6560716, "lng": -74.0595918 }],
      },
      {
        "id": 19,
        "nameSite": "Catedral-Zipaquira",
        "description": "bla bla bla bla",
        "rating": 10,
        "type": "Diversión",
        "ccomments": "16+",
        "address": "Calle 100# 13-21",
        "city": "Bogota",
        "country": "Colombia",
        "socialMedia": [{ "gmail": "sitio@gmail.com", "facebook": "sitio@gmail.com" }],
        "images": "https://www.tootay.com/wp-content/uploads/2017/07/600-13093.jpeg",
        "source": "https://www.kienyke.com/wp-content/uploads/2018/05/avistamientos.jpeg",
        "coordinates": [{ "lat": 4.6560716, "lng": -74.0595918 }],
      },
      {
        "id": 20,
        "nameSite": "Catedral-Zipaquira",
        "description": "bla bla bla bla",
        "rating": 10,
        "type": "Diversión",
        "ccomments": "16+",
        "address": "Calle 100# 13-21",
        "city": "Bogota",
        "country": "Colombia",
        "socialMedia": [{ "gmail": "sitio@gmail.com", "facebook": "sitio@gmail.com" }],
        "images": "https://hablemosdeculturas.com/wp-content/uploads/2017/12/Comida-Francesa-08.jpg",
        "source": "https://www.kienyke.com/wp-content/uploads/2018/05/avistamientos.jpeg",
        "coordinates": [{ "lat": 4.6560716, "lng": -74.0595918 }],
      },
    ],
    "fun": [
      {
        "id": 21,
        "nameSite": "Catedral-Zipaquira",
        "description": "bla bla bla bla",
        "rating": 10,
        "type": "Diversión",
        "ccomments": "16+",
        "address": "Calle 100# 13-21",
        "city": "Bogota",
        "country": "Colombia",
        "socialMedia": [{ "gmail": "sitio@gmail.com", "facebook": "sitio@gmail.com" }],
        "images": "https://www.ecestaticos.com/imagestatic/clipping/1ed/a44/1eda44daf5f75ca868b7eb9bf93396e4/por-que-el-desayuno-es-la-comida-mas-importante-si-quieres-estar-delgado.jpg?mtime=1500455115",
        "source": "https://www.kienyke.com/wp-content/uploads/2018/05/avistamientos.jpeg",
        "coordinates": [{ "lat": 4.6560716, "lng": -74.0595918 }],
      },
      {
        "id": 22,
        "nameSite": "Catedral-Zipaquira",
        "description": "bla bla bla bla",
        "rating": 10,
        "type": "Diversión",
        "ccomments": "16+",
        "address": "Calle 100# 13-21",
        "city": "Bogota",
        "country": "Colombia",
        "socialMedia": [{ "gmail": "sitio@gmail.com", "facebook": "sitio@gmail.com" }],
        "images": "https://blog.seccionamarilla.com.mx/wp-content/uploads/2017/11/comida_naviden%CC%83a-770x578.jpg",
        "source": "https://www.kienyke.com/wp-content/uploads/2018/05/avistamientos.jpeg",
        "coordinates": [{ "lat": 4.6560716, "lng": -74.0595918 }],
      },
      {
        "id": 23,
        "nameSite": "Catedral-Zipaquira",
        "description": "bla bla bla bla",
        "rating": 10,
        "type": "Diversión",
        "ccomments": "16+",
        "address": "Calle 100# 13-21",
        "city": "Bogota",
        "country": "Colombia",
        "socialMedia": [{ "gmail": "sitio@gmail.com", "facebook": "sitio@gmail.com" }],
        "images": "https://i1.wp.com/thehappening.com/wp-content/uploads/2017/01/comida-healthy.jpg?fit=1024%2C694&ssl=1",
        "source": "https://www.kienyke.com/wp-content/uploads/2018/05/avistamientos.jpeg",
        "coordinates": [{ "lat": 4.6560716, "lng": -74.0595918 }],
      },
      {
        "id": 24,
        "nameSite": "Catedral-Zipaquira",
        "description": "bla bla bla bla",
        "rating": 10,
        "type": "Diversión",
        "ccomments": "16+",
        "address": "Calle 100# 13-21",
        "city": "Bogota",
        "country": "Colombia",
        "socialMedia": [{ "gmail": "sitio@gmail.com", "facebook": "sitio@gmail.com" }],
        "images": "https://t2.rg.ltmcdn.com/es/images/4/2/6/los_15_platos_mas_tipicos_de_mexico_71624_600.jpg",
        "source": "https://www.kienyke.com/wp-content/uploads/2018/05/avistamientos.jpeg",
        "coordinates": [{ "lat": 4.6560716, "lng": -74.0595918 }],
      },
      {
        "id": 25,
        "nameSite": "Catedral-Zipaquira",
        "description": "bla bla bla bla",
        "rating": 10,
        "type": "Diversión",
        "ccomments": "16+",
        "address": "Calle 100# 13-21",
        "city": "Bogota",
        "country": "Colombia",
        "socialMedia": [{ "gmail": "sitio@gmail.com", "facebook": "sitio@gmail.com" }],
        "images": "https://www.tootay.com/wp-content/uploads/2017/07/600-13093.jpeg",
        "source": "https://www.kienyke.com/wp-content/uploads/2018/05/avistamientos.jpeg",
        "coordinates": [{ "lat": 4.6560716, "lng": -74.0595918 }],
      },
      {
        "id": 26,
        "nameSite": "Catedral-Zipaquira",
        "description": "bla bla bla bla",
        "rating": 10,
        "type": "Diversión",
        "ccomments": "16+",
        "address": "Calle 100# 13-21",
        "city": "Bogota",
        "country": "Colombia",
        "socialMedia": [{ "gmail": "sitio@gmail.com", "facebook": "sitio@gmail.com" }],
        "images": "https://hablemosdeculturas.com/wp-content/uploads/2017/12/Comida-Francesa-08.jpg",
        "source": "https://www.kienyke.com/wp-content/uploads/2018/05/avistamientos.jpeg",
        "coordinates": [{ "lat": 4.6560716, "lng": -74.0595918 }],
      },
    ],
    "shopping": [
      {
        "id": 27,
        "nameSite": "Catedral-Zipaquira",
        "description": "bla bla bla bla",
        "rating": 10,
        "type": "Diversión",
        "ccomments": "16+",
        "address": "Calle 100# 13-21",
        "city": "Bogota",
        "country": "Colombia",
        "socialMedia": [{ "gmail": "sitio@gmail.com", "facebook": "sitio@gmail.com" }],
        "images": "https://cdn.shopify.com/s/files/1/1381/2063/products/tour-de-compras-jersey-gardens_grande.jpg?v=1494523091",
        "source": "https://www.kienyke.com/wp-content/uploads/2018/05/avistamientos.jpeg",
        "coordinates": [{ "lat": 4.6560716, "lng": -74.0595918 }],
      },
      {
        "id": 28,
        "nameSite": "Catedral-Zipaquira",
        "description": "bla bla bla bla",
        "rating": 10,
        "type": "Diversión",
        "ccomments": "16+",
        "address": "Calle 100# 13-21",
        "city": "Bogota",
        "country": "Colombia",
        "socialMedia": [{ "gmail": "sitio@gmail.com", "facebook": "sitio@gmail.com" }],
        "images": "https://d8bwfgv5erevs.cloudfront.net/cdn/13/images/curso-de-logistica-de-compras-y-aprovisionamientos_l_primaria_1.jpg",
        "source": "https://www.kienyke.com/wp-content/uploads/2018/05/avistamientos.jpeg",
        "coordinates": [{ "lat": 4.6560716, "lng": -74.0595918 }],
      },
      {
        "id": 29,
        "nameSite": "Catedral-Zipaquira",
        "description": "bla bla bla bla",
        "rating": 10,
        "type": "Diversión",
        "ccomments": "16+",
        "address": "Calle 100# 13-21",
        "city": "Bogota",
        "country": "Colombia",
        "socialMedia": [{ "gmail": "sitio@gmail.com", "facebook": "sitio@gmail.com" }],
        "images": "https://www.incp.org.co/wp-content/uploads/2017/11/Compras-800x411.jpg",
        "source": "https://www.kienyke.com/wp-content/uploads/2018/05/avistamientos.jpeg",
        "coordinates": [{ "lat": 4.6560716, "lng": -74.0595918 }],
      },
      {
        "id": 30,
        "nameSite": "Catedral-Zipaquira",
        "description": "bla bla bla bla",
        "rating": 10,
        "type": "Diversión",
        "ccomments": "16+",
        "address": "Calle 100# 13-21",
        "city": "Bogota",
        "country": "Colombia",
        "socialMedia": [{ "gmail": "sitio@gmail.com", "facebook": "sitio@gmail.com" }],
        "images": "https://m.prensa.com/vivir/Compras-seguras_LPRIMA20171123_0106_27.jpg",
        "source": "https://www.kienyke.com/wp-content/uploads/2018/05/avistamientos.jpeg",
        "coordinates": [{ "lat": 4.6560716, "lng": -74.0595918 }],
      },
      {
        "id": 31,
        "nameSite": "Catedral-Zipaquira",
        "description": "bla bla bla bla",
        "rating": 10,
        "type": "Diversión",
        "ccomments": "16+",
        "address": "Calle 100# 13-21",
        "city": "Bogota",
        "country": "Colombia",
        "socialMedia": [{ "gmail": "sitio@gmail.com", "facebook": "sitio@gmail.com" }],
        "images": "https://www.tootay.com/wp-content/uploads/2017/07/600-13093.jpeg",
        "source": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRla2-w_TF3taQdL79iuZ3usJULOQaLX9uvipmDjEm-a8qxII76&s",
        "coordinates": [{ "lat": 4.6560716, "lng": -74.0595918 }],
      },
      {
        "id": 32,
        "nameSite": "Catedral-Zipaquira",
        "description": "bla bla bla bla",
        "rating": 10,
        "type": "Diversión",
        "ccomments": "16+",
        "address": "Calle 100# 13-21",
        "city": "Bogota",
        "country": "Colombia",
        "socialMedia": [{ "gmail": "sitio@gmail.com", "facebook": "sitio@gmail.com" }],
        "images": "https://smarterworkspaces.kyocera.es/blog/wp-content/uploads/2018/05/gestion-de-compras-770x577.jpg",
        "source": "https://www.kienyke.com/wp-content/uploads/2018/05/avistamientos.jpeg",
        "coordinates": [{ "lat": 4.6560716, "lng": -74.0595918 }],
      },
    ],
    "Health": [
      {
        "id": 33,
        "nameSite": "Catedral-Zipaquira",
        "description": "bla bla bla bla",
        "rating": 10,
        "type": "Diversión",
        "ccomments": "16+",
        "address": "Calle 100# 13-21",
        "city": "Bogota",
        "country": "Colombia",
        "socialMedia": [{ "gmail": "sitio@gmail.com", "facebook": "sitio@gmail.com" }],
        "images": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZ33eUwUuAHaDNn4-DhrACj1RS6ufAqqTPHHyHPrtQZ8xBKYT0uw&s",
        "source": "https://www.kienyke.com/wp-content/uploads/2018/05/avistamientos.jpeg",
        "coordinates": [{ "lat": 4.6560716, "lng": -74.0595918 }],
      },
      {
        "id": 34,
        "nameSite": "Catedral-Zipaquira",
        "description": "bla bla bla bla",
        "rating": 10,
        "type": "Diversión",
        "ccomments": "16+",
        "address": "Calle 100# 13-21",
        "city": "Bogota",
        "country": "Colombia",
        "socialMedia": [{ "gmail": "sitio@gmail.com", "facebook": "sitio@gmail.com" }],
        "images": "https://images.medicinenet.com/images/article/main_image/healthy-living2.jpg",
        "source": "https://www.kienyke.com/wp-content/uploads/2018/05/avistamientos.jpeg",
        "coordinates": [{ "lat": 4.6560716, "lng": -74.0595918 }],
      },
      {
        "id": 35,
        "nameSite": "Catedral-Zipaquira",
        "description": "bla bla bla bla",
        "rating": 10,
        "type": "Diversión",
        "ccomments": "16+",
        "address": "Calle 100# 13-21",
        "city": "Bogota",
        "country": "Colombia",
        "socialMedia": [{ "gmail": "sitio@gmail.com", "facebook": "sitio@gmail.com" }],
        "images": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT9JHkkyk8toNxbWQUhZR4GBMwK7ahYSomZUEZ2Bc-rS0Ct-PKC&s",
        "source": "https://www.kienyke.com/wp-content/uploads/2018/05/avistamientos.jpeg",
        "coordinates": [{ "lat": 4.6560716, "lng": -74.0595918 }],
      },
      {
        "id": 36,
        "nameSite": "Catedral-Zipaquira",
        "description": "bla bla bla bla",
        "rating": 10,
        "type": "Diversión",
        "ccomments": "16+",
        "address": "Calle 100# 13-21",
        "city": "Bogota",
        "country": "Colombia",
        "socialMedia": [{ "gmail": "sitio@gmail.com", "facebook": "sitio@gmail.com" }],
        "images": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTe1btS-ejII_9upBKmZdMJ3ZUB_3rH8U_YnoTCAPLDWvCRwRdu&s",
        "source": "https://www.kienyke.com/wp-content/uploads/2018/05/avistamientos.jpeg",
        "coordinates": [{ "lat": 4.6560716, "lng": -74.0595918 }],
      },
      {
        "id": 37,
        "nameSite": "Catedral-Zipaquira",
        "description": "bla bla bla bla",
        "rating": 10,
        "type": "Diversión",
        "ccomments": "16+",
        "address": "Calle 100# 13-21",
        "city": "Bogota",
        "country": "Colombia",
        "socialMedia": [{ "gmail": "sitio@gmail.com", "facebook": "sitio@gmail.com" }],
        "images": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTsEL6MIaMezpM8N0Lo6JGgss8LfC7k8til0kzAP75FoyAH8F9QmQ&s",
        "source": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTsEL6MIaMezpM8N0Lo6JGgss8LfC7k8til0kzAP75FoyAH8F9QmQ&s",
        "coordinates": [{ "lat": 4.6560716, "lng": -74.0595918 }],
      },
      {
        "id": 38,
        "nameSite": "Catedral-Zipaquira",
        "description": "bla bla bla bla",
        "rating": 10,
        "type": "Diversión",
        "ccomments": "16+",
        "address": "Calle 100# 13-21",
        "city": "Bogota",
        "country": "Colombia",
        "socialMedia": [{ "gmail": "sitio@gmail.com", "facebook": "sitio@gmail.com" }],
        "images": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTfNZxBYIixZSnqaCr1uVXPtAzkhGHEKoGNdRu1yeJ8SGakstE3&s",
        "source": "https://www.kienyke.com/wp-content/uploads/2018/05/avistamientos.jpeg",
        "coordinates": [{ "lat": 4.6560716, "lng": -74.0595918 }],
      },
    ],
    "pets": [
      {
        "id": 39,
        "nameSite": "Catedral-Zipaquira",
        "description": "bla bla bla bla",
        "rating": 10,
        "type": "Diversión",
        "ccomments": "16+",
        "address": "Calle 100# 13-21",
        "city": "Bogota",
        "country": "Colombia",
        "socialMedia": [{ "gmail": "sitio@gmail.com", "facebook": "sitio@gmail.com" }],
        "images": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZ33eUwUuAHaDNn4-DhrACj1RS6ufAqqTPHHyHPrtQZ8xBKYT0uw&s",
        "source": "https://www.kienyke.com/wp-content/uploads/2018/05/avistamientos.jpeg",
        "coordinates": [{ "lat": 4.6560716, "lng": -74.0595918 }],
      },
      {
        "id": 40,
        "nameSite": "Catedral-Zipaquira",
        "description": "bla bla bla bla",
        "rating": 10,
        "type": "Diversión",
        "ccomments": "16+",
        "address": "Calle 100# 13-21",
        "city": "Bogota",
        "country": "Colombia",
        "socialMedia": [{ "gmail": "sitio@gmail.com", "facebook": "sitio@gmail.com" }],
        "images": "https://images.medicinenet.com/images/article/main_image/healthy-living2.jpg",
        "source": "https://www.kienyke.com/wp-content/uploads/2018/05/avistamientos.jpeg",
        "coordinates": [{ "lat": 4.6560716, "lng": -74.0595918 }],
      },
      {
        "id": 41,
        "nameSite": "Catedral-Zipaquira",
        "description": "bla bla bla bla",
        "rating": 10,
        "type": "Diversión",
        "ccomments": "16+",
        "address": "Calle 100# 13-21",
        "city": "Bogota",
        "country": "Colombia",
        "socialMedia": [{ "gmail": "sitio@gmail.com", "facebook": "sitio@gmail.com" }],
        "images": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT9JHkkyk8toNxbWQUhZR4GBMwK7ahYSomZUEZ2Bc-rS0Ct-PKC&s",
        "source": "https://www.kienyke.com/wp-content/uploads/2018/05/avistamientos.jpeg",
        "coordinates": [{ "lat": 4.6560716, "lng": -74.0595918 }],
      },
      {
        "id": 42,
        "nameSite": "Catedral-Zipaquira",
        "description": "bla bla bla bla",
        "rating": 10,
        "type": "Diversión",
        "ccomments": "16+",
        "address": "Calle 100# 13-21",
        "city": "Bogota",
        "country": "Colombia",
        "socialMedia": [{ "gmail": "sitio@gmail.com", "facebook": "sitio@gmail.com" }],
        "images": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTe1btS-ejII_9upBKmZdMJ3ZUB_3rH8U_YnoTCAPLDWvCRwRdu&s",
        "source": "https://www.kienyke.com/wp-content/uploads/2018/05/avistamientos.jpeg",
        "coordinates": [{ "lat": 4.6560716, "lng": -74.0595918 }],
      },
      {
        "id": 43,
        "nameSite": "Catedral-Zipaquira",
        "description": "bla bla bla bla",
        "rating": 10,
        "type": "Diversión",
        "ccomments": "16+",
        "address": "Calle 100# 13-21",
        "city": "Bogota",
        "country": "Colombia",
        "socialMedia": [{ "gmail": "sitio@gmail.com", "facebook": "sitio@gmail.com" }],
        "images": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTsEL6MIaMezpM8N0Lo6JGgss8LfC7k8til0kzAP75FoyAH8F9QmQ&s",
        "source": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTsEL6MIaMezpM8N0Lo6JGgss8LfC7k8til0kzAP75FoyAH8F9QmQ&s",
        "coordinates": [{ "lat": 4.6560716, "lng": -74.0595918 }],
      },
      {
        "id": 44,
        "nameSite": "Catedral-Zipaquira",
        "description": "bla bla bla bla",
        "rating": 10,
        "type": "Diversión",
        "ccomments": "16+",
        "address": "Calle 100# 13-21",
        "city": "Bogota",
        "country": "Colombia",
        "socialMedia": [{ "gmail": "sitio@gmail.com", "facebook": "sitio@gmail.com" }],
        "images": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTfNZxBYIixZSnqaCr1uVXPtAzkhGHEKoGNdRu1yeJ8SGakstE3&s",
        "source": "https://www.kienyke.com/wp-content/uploads/2018/05/avistamientos.jpeg",
        "coordinates": [{ "lat": 4.6560716, "lng": -74.0595918 }],
      },
    ],
    "movie": [
      {
        "id": 45,
        "nameSite": "Catedral-Zipaquira",
        "description": "bla bla bla bla",
        "rating": 10,
        "type": "Diversión",
        "ccomments": "16+",
        "address": "Calle 100# 13-21",
        "city": "Bogota",
        "country": "Colombia",
        "socialMedia": [{ "gmail": "sitio@gmail.com", "facebook": "sitio@gmail.com" }],
        "images": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZ33eUwUuAHaDNn4-DhrACj1RS6ufAqqTPHHyHPrtQZ8xBKYT0uw&s",
        "source": "https://www.kienyke.com/wp-content/uploads/2018/05/avistamientos.jpeg",
        "coordinates": [{ "lat": 4.6560716, "lng": -74.0595918 }],
      },
      {
        "id": 46,
        "nameSite": "Catedral-Zipaquira",
        "description": "bla bla bla bla",
        "rating": 10,
        "type": "Diversión",
        "ccomments": "16+",
        "address": "Calle 100# 13-21",
        "city": "Bogota",
        "country": "Colombia",
        "socialMedia": [{ "gmail": "sitio@gmail.com", "facebook": "sitio@gmail.com" }],
        "images": "https://images.medicinenet.com/images/article/main_image/healthy-living2.jpg",
        "source": "https://www.kienyke.com/wp-content/uploads/2018/05/avistamientos.jpeg",
        "coordinates": [{ "lat": 4.6560716, "lng": -74.0595918 }],
      },
      {
        "id": 47,
        "nameSite": "Catedral-Zipaquira",
        "description": "bla bla bla bla",
        "rating": 10,
        "type": "Diversión",
        "ccomments": "16+",
        "address": "Calle 100# 13-21",
        "city": "Bogota",
        "country": "Colombia",
        "socialMedia": [{ "gmail": "sitio@gmail.com", "facebook": "sitio@gmail.com" }],
        "images": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT9JHkkyk8toNxbWQUhZR4GBMwK7ahYSomZUEZ2Bc-rS0Ct-PKC&s",
        "source": "https://www.kienyke.com/wp-content/uploads/2018/05/avistamientos.jpeg",
        "coordinates": [{ "lat": 4.6560716, "lng": -74.0595918 }],
      },
      {
        "id": 48,
        "nameSite": "Catedral-Zipaquira",
        "description": "bla bla bla bla",
        "rating": 10,
        "type": "Diversión",
        "ccomments": "16+",
        "address": "Calle 100# 13-21",
        "city": "Bogota",
        "country": "Colombia",
        "socialMedia": [{ "gmail": "sitio@gmail.com", "facebook": "sitio@gmail.com" }],
        "images": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTe1btS-ejII_9upBKmZdMJ3ZUB_3rH8U_YnoTCAPLDWvCRwRdu&s",
        "source": "https://www.kienyke.com/wp-content/uploads/2018/05/avistamientos.jpeg",
        "coordinates": [{ "lat": 4.6560716, "lng": -74.0595918 }],
      },
      {
        "id": 49,
        "nameSite": "Catedral-Zipaquira",
        "description": "bla bla bla bla",
        "rating": 10,
        "type": "Diversión",
        "ccomments": "16+",
        "address": "Calle 100# 13-21",
        "city": "Bogota",
        "country": "Colombia",
        "socialMedia": [{ "gmail": "sitio@gmail.com", "facebook": "sitio@gmail.com" }],
        "images": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTsEL6MIaMezpM8N0Lo6JGgss8LfC7k8til0kzAP75FoyAH8F9QmQ&s",
        "source": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTsEL6MIaMezpM8N0Lo6JGgss8LfC7k8til0kzAP75FoyAH8F9QmQ&s",
        "coordinates": [{ "lat": 4.6560716, "lng": -74.0595918 }],
      },
      {
        "id": 50,
        "nameSite": "Catedral-Zipaquira",
        "description": "bla bla bla bla",
        "rating": 10,
        "type": "Diversión",
        "ccomments": "16+",
        "address": "Calle 100# 13-21",
        "city": "Bogota",
        "country": "Colombia",
        "socialMedia": [{ "gmail": "sitio@gmail.com", "facebook": "sitio@gmail.com" }],
        "images": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTfNZxBYIixZSnqaCr1uVXPtAzkhGHEKoGNdRu1yeJ8SGakstE3&s",
        "source": "https://www.kienyke.com/wp-content/uploads/2018/05/avistamientos.jpeg",
        "coordinates": [{ "lat": 4.6560716, "lng": -74.0595918 }],
      },
    ],
};

const composeEnhancers = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ || compose;
const store = createStore(reducer, initialState, composeEnhancers());

ReactDOM.render(
  <Provider store={store}>
    <App />
  </Provider>,
  document.getElementById('app'),
);
